import Head from 'next/head';
import ColorModeSwitch from '@/components/ColorModeSwitch';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <ColorModeSwitch />
        <h1>Home Page</h1>
      </main>
    </>
  );
}
